version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    groups:
      opentelemetry-collector:
        applies-to: "version-updates"
        patterns:
          - "go.opentelemetry.io/collector*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
